if(NOT WIN32 OR NOT MINGW)
    message(FATAL_ERROR "The static OpenSSL hook requires the Windows MinGW build")
endif()
find_package(PkgConfig REQUIRED)
pkg_check_modules(LAMPAUA_OPENSSL REQUIRED openssl)
pkg_get_variable(lampaua_openssl_include openssl includedir)
if(NOT lampaua_openssl_include STREQUAL OPENSSL_INCLUDE_DIR)
    message(FATAL_ERROR "OpenSSL pkg-config metadata does not match the selected SDK")
endif()
# CMake's Windows FindOpenSSL omits private compression dependencies. Keep
# them after libssl/libcrypto for GNU ld, in both probes and imported targets.
set(lampaua_openssl_dependencies ${LAMPAUA_OPENSSL_STATIC_LIBRARIES} ${LAMPAUA_OPENSSL_STATIC_LDFLAGS_OTHER})
list(REMOVE_ITEM lampaua_openssl_dependencies ssl crypto)
foreach(variable OPENSSL_SSL_LIBRARIES OPENSSL_CRYPTO_LIBRARIES OPENSSL_LIBRARIES)
    list(APPEND ${variable} ${lampaua_openssl_dependencies})
endforeach()
set_property(TARGET OpenSSL::Crypto APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${lampaua_openssl_dependencies})
unset(lampaua_openssl_include)
unset(lampaua_openssl_dependencies)
